# DUT.Models.Commentary.dcm.yml

DUT\Models\Commentary:
  type: entity
  table: Commentary

  id:
    idCommentary:
      type: integer
      associationKey: true
      generator:
        strategy: auto

    idPost:
      type: integer

  fields:
    pseudo:
      type: string
      length: 32
      column: pseudo

    content:
      type: text
      column: content

    postDate:
      type: string
      lenght: 10
      column: postDate
