# DUT.Models.Post.dcm.yml

DUT\Models\Post:
  type: entity
  table: Post

  id:
    idPost:
      generator:
        strategy: auto

  fields:
    title:
      type: string
      lenght: 128
      column: title

    content:
      type: text
      column: content

    postDate:
      type: string
      lenght: 10
      column: postDate

    image:
      type: string
      lenght: 64
      column: image
