# DUT.Models.Commentary.dcm.yml

DUT\Models\Commentary:
  type: entity
  table: Commentary

  id:
    idPost:
      associationKey: true

    idCommentary:
      type: integer
      associationKey: true
      generator:
        strategy: auto

  fields:
    pseudo:
      type: string
      length: 32
      column: pseudo

    content:
      type: text
      column: content
